version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  build-and-lint:
    docker:
      - image: cimg/node:22.11
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Enable Corepack
          command: corepack enable
      - run:
          name: Install dependencies
          command: cd web-react && yarn install --immutable
      - run:
          name: Lint
          command: cd web-react && yarn lint
      - run:
          name: Build
          command: cd web-react && yarn build

workflows:
  ci:
    jobs:
      - build-and-lint


